services:
  consul:
    init: true
    build:
      context: .
      dockerfile: docker/consul/Dockerfile
    entrypoint:
      - consul
      - agent
      - -client
      - 0.0.0.0
      - -server
      - -ui
      - -dev
    ports:
      - '8500:8500'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
      interval: 5s
